FROM proglab/ubuntu-dev-quickfix:2.0 AS quickfix

WORKDIR /tmp
RUN git clone https://justin:8037873@code.prog-lab.com/justin/FIXClient.git && \
    cd FIXClient && \
    mkdir build && \
    cd build && \
    cmake .. && \
    make     

FROM ubuntu:20.04 AS base

RUN apt-get update -y && apt-get upgrade -y && apt-get install gdb -y

COPY --from=quickfix /usr/local/bin /usr/local/bin
COPY --from=quickfix /usr/local/include/quickfix /usr/local/include/quickfix
COPY --from=quickfix /usr/local/lib/libquickfix.so.17.0.0 /usr/local/lib
COPY --from=quickfix /usr/local/share/quickfix /usr/local/share/quickfix
COPY --from=quickfix /tmp/FIXClient/build/src/fixclient /usr/local/bin

WORKDIR /usr/local/lib
RUN ln -s libquickfix.so.17.0.0 libquickfix.so.17 && \
    ln -s libquickfix.so.17.0.0 libquickfix.so && \
    ldconfig