
FROM nodered/node-red
#RUN npm install node-red-node-email
#RUN cd ~/.node-red
WORKDIR /usr/src/node-red
RUN npm config set proxy null
RUN npm config set https-proxy null
RUN npm config set registry https://registry.npmjs.org
#RUN npm install node-red-node-email
